spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheet_db
    username: postgres
    password: symphony
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: my-super-secret-jwt-key-that-is-very-long-and-secure-for-hs512-algorithm-and-must-be-at-least-512-bits-long-1234567890
      expiration: 86400000

server:
  port: 8080

logging:
  level:
    com.servicesymphony.timesheet: DEBUG